order:
    path:     /
    defaults: { _controller: "ProjectMoviesBundle:Order:index" }

order_show:
    path:     /{id}/show
    defaults: { _controller: "ProjectMoviesBundle:Order:show" }

order_new:
    path:     /new
    defaults: { _controller: "ProjectMoviesBundle:Order:new" }

order_create:
    path:     /create
    defaults: { _controller: "ProjectMoviesBundle:Order:create" }
    methods:  POST

order_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProjectMoviesBundle:Order:edit" }

order_update:
    path:     /{id}/update
    defaults: { _controller: "ProjectMoviesBundle:Order:update" }
    methods:  [POST, PUT]

order_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProjectMoviesBundle:Order:delete" }
    methods:  [POST, DELETE]
