Project\MoviesBundle\Entity\Actor:
  type: entity
  #repositoryClass: Project\MoviesBundle\Repository\ActorRepository‏
  detect_relations: true
  table: actors
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    name:
      type: string
      length: 45
    surname:
      type: string
      length: 45
    movies_id:
      type: integer
      nullable: true
    genre:
      type: string
      length: 25
