Project\MoviesBundle\Entity\Genre:
  type: entity
  #repositoryClass: Project\MoviesBundle\Repository\GenreRepository‏
  detect_relations: true
  table: genres
  fields:
    genre:
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
      length: 45
